sudo: false
language: python
python:
- '3.6'
- '3.4'
- '2.7'
env:
- DJANGO_VERSION=1.8.*
- DJANGO_VERSION=1.9.*
- DJANGO_VERSION=1.10.*
- DJANGO_VERSION=1.11.*

before_script:
- pip install -U Django==$DJANGO_VERSION
- pip install -e .
- pip install pycodestyle
- pip install coverage
- pip install python-coveralls
- npm install -g jshint
- cp travis-ci/manage.py manage.py

script:
- pycodestyle supporttools/
- jshint supporttools/static/supporttools/js/ --verbose
- python -m compileall supporttools/
- coverage run --source=supporttools manage.py test supporttools
after_script:
- coveralls
notifications:
  email: false
before_deploy:
- find supporttools/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > supporttools/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: QSvfDjMYBNr5zZdek6k4Z+ePBg4JPEbdXEXMZzefGlvevSvrNDgjt5DzjFa+P7HkyNSH1BeeYjyGGqxY0F1GZ1s2629dHl9CT33gG0nd9iWgQ6yJe7lC6LYjJz8YAl5xJCY2as8LwclbL5OalesAXx2/djs5wL268gCU+Lm9h9A=
  on:
    tags: true
    python: '2.7'
    condition: $DJANGO_VERSION = 1.10.*
